# Framework for running automated tests on OSB using Travis-CI, see https://github.com/borismarin/osb-model-validation
# Still in development, subject to change without notice!!

language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all
    
    
    

